#cloud-config
runcmd:
#Sumo Logic installation folder for ubuntu machines
 - mkdir /usr/local/SumoCollector
write_files:
- encoding: b64
  content: ${sources} 
  path: /usr/local/SumoCollector/sources.json
#The source file provides desired metrics which must be in .json format  
runcmd:
 - wget "https://collectors.sumologic.com/rest/download/linux/64" -O SumoCollector.sh
 - chmod +x SumoCollector.sh
 - ./SumoCollector.sh -q -Vsumo.token_and_url=${token} -VsyncSources=sources.json -Vephemeral=false

